### ISSUE TITLE
Support for `kind: GitRepository` as sourceRef

### ISSUE THREAD

**Issue by Zaunei** [DoodleScheduling/flux-build#342]
First of all, thank you very much for this super helpful tool!
In some cases charts are unfortunately not offered as Helm Repo/ OCI Artifact and you have to fallback on Git Repos with a `sourceRef` to `kind: GitRepository`. 
flux-build does not seem to be able to handle this. Is there anything against implementing this?

Example:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: local-static-provisioner
  namespace: flux-system
spec:
  interval: 3m
  ref:
    tag: "v2.8.0"
  url: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-static-provisioner
  namespace: local-static-provisioner
spec:
  releaseName: local-static-provisioner
  interval: 1m
  chart:
    spec:
      chart: helm/provisioner
      sourceRef:
        name: local-static-provisioner
        kind: GitRepository
        namespace: flux-system
```
